# Test Scenarios for Validation Framework
# Defines specific test cases for comprehensive validation

scenarios:
  
  # Basic Performance Tests
  nominal_single_star:
    description: "Single bright star at field center"
    stars:
      - magnitude: 3.0
        ra_deg: 0.0
        dec_deg: 0.0
        field_angle_deg: 0.0
    psf_generation: "Gen_1"
    trials: 100
    
  field_edge_performance:
    description: "Star performance at field edge"
    stars:
      - magnitude: 3.0
        ra_deg: 0.0
        dec_deg: 0.0
        field_angle_deg: 14.0
    psf_generation: "Gen_1" 
    trials: 100

  # Star Density Tests
  sparse_field:
    description: "Sparse star field - 4 stars wide separation"
    catalog_file: "data/catalogs/sparse_4_stars_wide_separation.csv"
    attitude_variations: 50
    
  dense_field:
    description: "Dense star field - high clutter"
    catalog_file: "data/catalogs/high_clutter_10_stars.csv"
    attitude_variations: 50
    
  clustered_field:
    description: "Challenging clustered star configuration"
    catalog_file: "data/catalogs/challenging_8_stars_clustered.csv"
    attitude_variations: 50

  # Magnitude Range Tests  
  bright_stars:
    description: "Bright star performance (mag 2-4)"
    magnitude_range: [2.0, 4.0]
    field_angles: [0, 5, 10, 14]
    trials_per_config: 25
    
  faint_stars:
    description: "Faint star performance (mag 5-6)" 
    magnitude_range: [5.0, 6.0]
    field_angles: [0, 5, 10, 14]
    trials_per_config: 25
    
  limiting_magnitude:
    description: "Determine limiting magnitude for detection"
    magnitude_range: [4.0, 8.0]
    magnitude_step: 0.2
    field_angle_deg: 0.0
    trials_per_magnitude: 50

  # Environmental Conditions
  nominal_environment:
    description: "Nominal space environment"
    temperature_c: -20
    radiation_dose: 0.0
    vibration_level: 0.0
    scenario_file: "outputs/perturbation_analysis/nominal_space_environment_scenario.json"
    
  harsh_environment:
    description: "Harsh space environment with degradation"
    temperature_c: -40
    radiation_dose: 100.0  # kRad
    vibration_level: 1.0   # g RMS
    scenario_file: "outputs/perturbation_analysis/harsh_environment_scenario.json"

  # Attitude Coverage Tests
  attitude_grid:
    description: "Systematic attitude grid coverage"
    ra_range: [0, 360]    # degrees
    dec_range: [-90, 90]  # degrees  
    roll_range: [0, 360]  # degrees
    grid_spacing: 30      # degrees
    stars_per_attitude: 5
    
  random_attitudes:
    description: "Random attitude Monte Carlo"
    n_samples: 1000
    uniform_sphere_sampling: true
    magnitude_range: [3.0, 5.0]

  # Algorithm Comparison Tests
  algorithm_benchmark:
    description: "Compare against literature benchmarks"
    reference_algorithms: ["Liebe", "Pyramid", "Grid"]
    test_cases: ["sparse_field", "dense_field", "bright_stars"]
    
  # Stress Tests
  low_snr_stress:
    description: "Low SNR stress test"
    magnitude_range: [6.0, 7.5]
    noise_multiplier: 2.0
    field_angles: [0, 7, 14]
    
  geometric_stress:
    description: "Challenging geometric configurations"
    min_star_separation_arcsec: 30  # Very close stars
    max_star_separation_deg: 0.5    # All stars in small region
    magnitude_range: [4.0, 6.0]

# Scenario Groups for Batch Execution
scenario_groups:
  
  quick_validation:
    description: "Fast validation for CI/CD"
    scenarios: ["nominal_single_star", "bright_stars"]
    reduced_trials: 10
    
  comprehensive_validation:
    description: "Full validation suite"
    scenarios: ["sparse_field", "dense_field", "clustered_field", 
                "bright_stars", "faint_stars", "attitude_grid"]
    
  performance_characterization:
    description: "Performance characterization for presentations"
    scenarios: ["limiting_magnitude", "field_edge_performance", 
                "algorithm_benchmark", "environmental_conditions"]
    
  stress_testing:
    description: "Stress testing and edge cases"
    scenarios: ["low_snr_stress", "geometric_stress", "harsh_environment"]

# Execution Parameters
execution:
  default_group: "comprehensive_validation"
  parallel_scenarios: true
  max_concurrent_scenarios: 4
  timeout_per_scenario_minutes: 10
  auto_save_interval_minutes: 5